// ============ Chrome: Nav, SideMeta, Footer, Lightbox ============

function Nav({ route, go }) {
  const [menuOpen, setMenuOpen] = React.useState(false);
  const progressRef = React.useRef(null);
  const links = [
    { id: "home", label: "Home" },
    { id: "archive", label: "Archive" },
    { id: "about", label: "About" },
    { id: "contact", label: "Contact" },
  ];

  // Close mobile menu on route change
  React.useEffect(() => { setMenuOpen(false); }, [route]);

  // Lock body scroll while mobile menu is open
  React.useEffect(() => {
    if (menuOpen) document.body.classList.add("nav-menu-open");
    else document.body.classList.remove("nav-menu-open");
    return () => document.body.classList.remove("nav-menu-open");
  }, [menuOpen]);

  // Scroll progress bar — width grows as user scrolls the page
  React.useEffect(() => {
    const bar = progressRef.current;
    if (!bar) return;
    let raf;
    const update = () => {
      const h = document.documentElement;
      const scrollable = (h.scrollHeight - h.clientHeight) || 1;
      const pct = Math.max(0, Math.min(1, h.scrollTop / scrollable));
      bar.style.transform = `scaleX(${pct})`;
      raf = null;
    };
    const onScroll = () => { if (!raf) raf = requestAnimationFrame(update); };
    update();
    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("resize", onScroll);
    return () => {
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onScroll);
      if (raf) cancelAnimationFrame(raf);
    };
  }, [route]);

  return (
    <nav className={"nav" + (menuOpen ? " nav-open" : "")}>
      <div ref={progressRef} className="nav-progress" aria-hidden="true" />
      <a className="nav-brand" href="#/home" data-cursor="hover"
         onClick={(e) => { e.preventDefault(); go("home"); setMenuOpen(false); }}>
        Alston <span className="italic">Shi</span>
      </a>
      <button
        className={"nav-hamburger" + (menuOpen ? " open" : "")}
        aria-label={menuOpen ? "Close menu" : "Open menu"}
        aria-expanded={menuOpen}
        onClick={() => setMenuOpen(!menuOpen)}
        data-cursor="hover">
        <span></span><span></span><span></span>
      </button>
      <div
        className="nav-backdrop"
        aria-hidden="true"
        onClick={() => setMenuOpen(false)}
      />
      <div className={"nav-links" + (menuOpen ? " open" : "")}>
        {links.map((l) => (
          <a key={l.id}
             href={"#/" + l.id}
             className={"nav-link" + (route === l.id ? " active" : "")}
             data-cursor="hover"
             onClick={(e) => { e.preventDefault(); go(l.id); setMenuOpen(false); }}>
            {l.label}
          </a>
        ))}
        <a href="/personal/" className="nav-link nav-link-ext" data-cursor="hover" title="Digital portfolio">
          Digital Portfolio <span className="ext-arrow" aria-hidden="true">↗</span>
        </a>
      </div>
    </nav>
  );
}

function SideMeta({ route }) {
  const idx = ({ home: "01", archive: "02", about: "03", contact: "04" })[route] || "01";
  const label = ({ home: "Index", archive: "Archive", about: "About", contact: "Contact" })[route] || "Index";
  return (
    <div className="side-meta">
      N° {idx} &nbsp;·&nbsp; {label} &nbsp;·&nbsp; MMXXV
    </div>
  );
}

function Footer({ go }) {
  return (
    <footer className="site-footer site-footer-simple">
      <a className="footer-brand-mark" href="#/home" data-cursor="hover"
         onClick={(e) => { e.preventDefault(); go("home"); }}>
        Alston <span className="italic">Shi</span>
      </a>
      <nav className="footer-nav" aria-label="Footer navigation">
        <a href="#/archive" data-cursor="hover" onClick={(e) => { e.preventDefault(); go("archive"); }}>Archive</a>
        <a href="#/about" data-cursor="hover" onClick={(e) => { e.preventDefault(); go("about"); }}>About</a>
        <a href="#/contact" data-cursor="hover" onClick={(e) => { e.preventDefault(); go("contact"); }}>Contact</a>
        <a href="/personal/" data-cursor="hover" className="nav-link-ext" title="Digital portfolio">Digital Portfolio <span aria-hidden="true">↗</span></a>
      </nav>
      <div className="footer-copy dim">© 2026 Alston Shi. All rights reserved.</div>
    </footer>
  );
}

// ---- PhotoImg: responsive <picture> with AVIF / WebP / JPG fallbacks ----
// Given a src like "images/Japan/IMG_2564.JPG", emits <picture> referencing
// the precompiled -480/-960/-1920 variants generated by scripts/optimize-images.js.
// Paths that don't look like one of our optimized sources fall through to a
// plain <img>.
function PhotoImg({ src, alt, className, style, sizes = "100vw", loading = "lazy", decoding = "async", ...rest }) {
  const m = typeof src === "string" && /^(.+)\.(jpe?g|png)$/i.exec(src);
  if (!m) {
    return <img src={src} alt={alt} className={className} style={style} loading={loading} decoding={decoding} {...rest} />;
  }
  const base = m[1];
  const widths = [480, 960, 1920];
  const set = (ext) => widths.map((w) => `${base}-${w}.${ext} ${w}w`).join(", ");
  return (
    <picture>
      <source type="image/avif" srcSet={set("avif")} sizes={sizes} />
      <source type="image/webp" srcSet={set("webp")} sizes={sizes} />
      <img src={src} alt={alt} className={className} style={style} loading={loading} decoding={decoding} {...rest} />
    </picture>
  );
}

// ---- Lightbox ----
function Lightbox({ items, index, onClose, onPrev, onNext }) {
  const drag = React.useRef({ active: false, startX: 0, startY: 0, dx: 0 });
  const wrapRef = React.useRef(null);

  React.useEffect(() => {
    if (index == null) return;
    const onKey = (e) => {
      if (e.key === "Escape") onClose();
      if (e.key === "ArrowLeft") onPrev();
      if (e.key === "ArrowRight") onNext();
    };
    window.addEventListener("keydown", onKey);
    document.body.style.overflow = "hidden";
    return () => {
      window.removeEventListener("keydown", onKey);
      document.body.style.overflow = "";
    };
  }, [index, onClose, onPrev, onNext]);

  const onLbPointerDown = (e) => {
    if (e.target.closest("button")) return;
    drag.current = { active: true, startX: e.clientX, startY: e.clientY, dx: 0 };
  };

  const onLbPointerMove = (e) => {
    if (!drag.current.active) return;
    const dx = e.clientX - drag.current.startX;
    const dy = e.clientY - drag.current.startY;
    drag.current.dx = dx;
    if (Math.abs(dx) > Math.abs(dy) && Math.abs(dx) > 8) {
      const wrap = wrapRef.current;
      if (wrap) {
        const t = Math.min(1, Math.abs(dx) / 160);
        wrap.style.transition = "none";
        wrap.style.transform = `scale(${1 - t * 0.03}) translateX(${dx * 0.08}px)`;
        wrap.style.filter = `blur(${t * 2.5}px)`;
        const lb = wrap.closest(".lightbox");
        if (lb) lb.classList.add("scrubbed");
      }
    }
  };

  const onLbPointerUp = (e) => {
    if (!drag.current.active) return;
    const { dx, startY } = drag.current;
    const dy = e.clientY - startY;
    drag.current.active = false;

    const wrap = wrapRef.current;
    const swiped = Math.abs(dx) >= 50 && Math.abs(dx) > Math.abs(dy);

    if (wrap) {
      if (swiped) {
        wrap.style.transition = "";
        wrap.style.transform = "";
        wrap.style.filter = "";
      } else {
        // Restore transition then clear so the snap-back animates
        requestAnimationFrame(() => {
          if (wrap) wrap.style.transition = "";
          requestAnimationFrame(() => {
            if (wrap) { wrap.style.transform = ""; wrap.style.filter = ""; }
          });
        });
      }
    }

    if (swiped) { if (dx < 0) onNext(); else onPrev(); }
  };

  const onLbClick = (e) => {
    // Suppress close if the pointer moved — it was a drag, not a tap
    if (Math.abs(drag.current.dx) > 10) { drag.current.dx = 0; return; }
    onClose();
  };

  const item = index != null ? items[index] : null;

  return (
    <div
      className={"lightbox" + (index != null ? " open" : "")}
      onClick={onLbClick}
      onPointerDown={onLbPointerDown}
      onPointerMove={onLbPointerMove}
      onPointerUp={onLbPointerUp}
      onPointerCancel={onLbPointerUp}
      data-cursor="hover"
    >
      {item && (
        <React.Fragment>
          <div className="lightbox-counter">
            {String(index + 1).padStart(3, "0")} / {String(items.length).padStart(3, "0")}
          </div>
          <button className="lightbox-close" onClick={(e) => { e.stopPropagation(); onClose(); }} data-cursor="hover">
            <span>Close</span>
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1"><path d="M1 1l12 12M13 1L1 13"/></svg>
          </button>

          <button className="lightbox-nav prev" onClick={(e) => { e.stopPropagation(); onPrev(); }} data-cursor="hover">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.2"><path d="M15 5l-8 7 8 7"/></svg>
          </button>
          <button className="lightbox-nav next" onClick={(e) => { e.stopPropagation(); onNext(); }} data-cursor="hover">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.2"><path d="M9 5l8 7-8 7"/></svg>
          </button>

          <div className="lightbox-img-wrap" ref={wrapRef} onClick={(e) => e.stopPropagation()}>
            {/* key remounts the picture on prev/next so the crossfade
                animation plays — without it the photo swaps instantly. */}
            <PhotoImg key={item.src} className="lightbox-img" src={item.src} alt={item.title} sizes="80vw" loading="eager" />
          </div>

          <div className="lightbox-hint" aria-hidden="true">
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4"><path d="M15 5l-8 7 8 7"/></svg>
            <span>Drag to scrub</span>
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4"><path d="M9 5l8 7-8 7"/></svg>
          </div>

          <div className="lightbox-strip">
            <div className="block">
              <div className="label ochre">{item.country} · {item.city}</div>
              <div className="title">{item.title}</div>
            </div>
            <div className="block" style={{ alignItems: "flex-end", textAlign: "right" }}>
              {/* camera/year are optional in the data model — render only what
                  exists so there's no empty line or dangling "· Frame" separator */}
              {item.camera && <div className="label">{item.camera}</div>}
              <div className="label dim">{item.year ? `${item.year} · ` : ""}Frame {String(index + 1).padStart(3, "0")}</div>
            </div>
          </div>
        </React.Fragment>
      )}
    </div>
  );
}

// ---- Featured stories — sticky editorial captions over tall photo cells ----
// Three picks from PORTFOLIO render as single-column 100vh frames. The caption
// `position: sticky; top: <nav-h>` so as the user scrolls the story, the title
// stays pinned to the top of the viewport for the duration of that photo's
// scroll range, then yields when the next story begins.
function FeaturedStories({ onOpenLightbox }) {
  const PICKS = [
    { file: "Japan/IMG_0544.JPG", kicker: "I · Canal in Spring",          lede: "Kyoto in April — the boat moving slowly enough to count the petals on the water." },
    { file: "China/IMG_9089.JPG", kicker: "II · Temple Incense",          lede: "Smoke and afternoon light. The kind of room where you remember to be quiet." },
    { file: "Japan/IMG_5583.JPG", kicker: "III · Dotonbori After Dark",   lede: "Reflections breaking apart in the canal — every shop sign trying to outshout the next." },
  ];
  const items = PICKS
    .map((p) => ({ ...p, item: window.PORTFOLIO_BY_FILE && window.PORTFOLIO_BY_FILE[p.file] }))
    .filter((p) => p.item);

  if (!items.length) return null;

  return (
    <section className="featured-stories" aria-label="Featured stories">
      {items.map((s, i) => {
        const idx = window.PORTFOLIO.findIndex((p) => p === s.item);
        return (
          <div key={i} className="fs-story">
            <div className="fs-meta">
              <div className="fs-kicker">{s.kicker}</div>
              <h2 className="fs-title">{s.item.title}</h2>
              <p className="fs-lede">{s.lede}</p>
              <div className="fs-loc">{s.item.country} · {s.item.city}</div>
            </div>
            <button
              className="fs-photo"
              onClick={() => onOpenLightbox && onOpenLightbox(idx)}
              data-cursor="view"
              data-cursor-label="Open"
              aria-label={`Open ${s.item.title}`}
            >
              <PhotoImg src={s.item.src} alt={s.item.title} sizes="(max-width: 900px) 92vw, 60vw" loading="lazy" />
            </button>
          </div>
        );
      })}
    </section>
  );
}

// ---- Animated section divider — hairlines draw in on scroll ----
function SectionDivider({ mark = "◆", numeral, label }) {
  const ref = React.useRef(null);
  React.useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const io = new IntersectionObserver(([e]) => {
      if (e.isIntersecting) {
        el.classList.add("in");
        io.disconnect();
      }
    }, { threshold: 0.3 });
    io.observe(el);
    return () => io.disconnect();
  }, []);

  return (
    <div ref={ref} className="section-divider" aria-hidden="true">
      <span className="sd-line sd-line-left" />
      <span className="sd-center">
        {numeral && <span className="sd-numeral">{numeral}</span>}
        <span className="sd-mark">{mark}</span>
        {label && <span className="sd-label">{label}</span>}
      </span>
      <span className="sd-line sd-line-right" />
    </div>
  );
}

Object.assign(window, { Nav, SideMeta, Footer, Lightbox, SectionDivider, PhotoImg, FeaturedStories });
